### ISSUE TITLE
Why is the node app using both Next.js and Koa?

### ISSUE THREAD

**Issue by joshbedo** [Shopify/shopify-cli#1153]
Just wondering why Next.js and Koa are being used together? It seems like Next.js alone with api/pages would be able to handle everything. For example, the Koa API could be the Next.js API. This would lower the amount of dependencies that need maintained in the future.

**Comment by npc-adrian** [comment]
I'd be interested to know about this too.  I'm an occasional JS programmer - so by no means an expert - but it looks to me like a deliberate separation fo concerns designed for extensibility.  The koa middleware is used to provide a generic set of services (auth, graphql proxy etc) that can underpin an application written in any framework you like.  

As it happens, the cli scaffolds a next+React app but there's no reason why you couldn't inject a Vue (for instance) app or something else.

See `server/server.js` in your generated app

```javascript
// line 16
const app = next({
  dev,
});
const handle = app.getRequestHandler(); // could be a root handler for any framework

// line 63
router.get("(.*)", verifyRequest(), async (ctx) => {
  await handle(ctx.req, ctx.res);
  ctx.respond = false;
  ctx.res.statusCode = 200;
});
```

On the other hand, it could just be a historical accident and everything is moving towards Next.

If someone who knows the design and history could checkin on this please, it would be really helpful.

**Comment by paulomarg** [comment]
Hey folks, thanks for these comments.

The example app is using both koa and next.js mostly for historical reasons, since that package combination was needed when it was first written. We've underpinned the existing app with our new Node library (https://github.com/Shopify/shopify-node-api) to make sure that the app is using our latest features, but it is only meant to speed up the process of getting started with an app for partners.

The new library was written in a framework-agnostic way so that apps don't necessarily have to use a specific backend framework, to enable developers to use whichever stack they'd prefer to work with.

That being said, we're always looking to improve our offerings, and we may change the app to use a different backend stack in the future.

**Comment by npc-adrian** [comment]
Thanks for clearing that up @paulomarg

**Comment by gilesbutler** [comment]
Hey @paulomarg,

It would be great to have a version of the scaffold that doesn't include React. As a Vue developer it's hard to know what needs to be ripped out of the boilerplate that's related to React/Next and what needs to stay to use with Vue.

I think same goes for the backend as well. We don't use Koa so it would be great to have a scaffold that is more flexible :)

Thanks
