### ISSUE TITLE
Unable to access pages other than index & connResetException in console

### ISSUE THREAD

**Issue by ScottJr** [Shopify/shopify-cli#1154]
# Issue summary

Performing a clean install of `shopify create node` does not work as prescribed in the docs or following the [Build a Shopify App with Node and React](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris). I've followed @paulomarg 's [suggestions to follow the demo app setup](https://github.com/Shopify/koa-shopify-auth/issues/61#issuecomment-790664587) (particularly steps 5-7) exactly as prescribed. I've cloned those repos as they in the tutorial and follow all the basic setup instructions and sill get the same result.

I've seen various threads around here that relate to the following issues happening:

1. You cannot access any other pages other than index. Here is a [discussion](https://github.com/Shopify/koa-shopify-auth/issues/61) about this issue on KOA. But there really isn't a fix that is implemented (especially removing KOA and using the approach suggested of not routing all requests to `/`). This issue was also brought up [here](https://github.com/Shopify/shopify-app-cli/issues/1145) and was closed because "I will close this issue since this is not an actual bug in the CLI or Node app.". Another user in the KOA issue reported the [same problem with a clean install](https://github.com/Shopify/koa-shopify-auth/issues/61#issuecomment-792809587)
2. Connection Reset errors. This issue has been talked about [here](https://github.com/Shopify/shopify-app-cli/issues/1047) without resolution. This is logged to the console on every request:

```
  Error: aborted
      at connResetException (node:internal/errors:631:14)
      at abortIncoming (node:_http_server:578:17)
      at socketOnEnd (node:_http_server:593:5)
      at Socket.emit (node:events:388:22)
      at endReadableNT (node:internal/streams/readable:1305:12)
      at processTicksAndRejections (node:internal/process/task_queues:80:21)
```

Are these issues being worked on and there isn't a solution or am I missing something?

**Comment by paulomarg** [comment]
Hey @ScottJr, let me see if I can help:

Any time you load a new page (as in, change the URL), a request is fired to the server. If the route that handles that request is running the `verifyRequest` middleware, that request will fail, because that middleware only passes if a request originates from an App Bridge `authenticatedFetch` call. Since you have to first load a page to create your App Bridge instance, any requests that load a server-rendered page needs to be unauthenticated (i.e. not use `verifyRequest`).

Alternatively, you can use a `ClientRouter` from App Bridge in your app to intercept URL changes and load them in the client side without firing a request to the server - therefore keeping your App Bridge instance and the ability to call `authenticatedFetch`. You can check out [the tutorial](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris#add-the-client-router) for more information on that.

You are correct in your statement that the app generated by the CLI doesn't include a `ClientRouter` and will end up hitting the server for other pages when one tries to load them. We'll add the component to avoid this sort of problem in the future.

As for the connection reset error, unfortunately there is very little to go on in that error message. We haven't seen this error before, and it seems to be coming from node, so it may not stem from the app. Do the requests still work despite the error message?

Hope this helps!

**Comment by chihirot0109** [comment]
In our case, ClientRouter and RoutePropagator are implemented successfully and router change in the production environment has no problem. However the route change always redirects to `/auth` only when I run `shopify serve`
