### ISSUE TITLE
CLI Wiki Improvements

### ISSUE THREAD

**Issue by carmelal** [Shopify/shopify-cli#1251]
# Issue summary
I came across my document of CLI wiki improvements from when I used it to implement the Themes project type. Here are the notes I took on improvements:
* Prereq task loaded as string, should be a symbol ([x](https://github.com/Shopify/shopify-app-cli/wiki/Tasks#prerequisite-task))
* Forms aren't loaded in `cli.rb` ([x](https://github.com/Shopify/shopify-app-cli/wiki/Form-Input))
* Loading for `creator` in `cli.rb` is out of date, was changed in [this](https://github.com/Shopify/shopify-app-cli/pull/958) PR ([x](https://github.com/Shopify/shopify-app-cli/wiki/Starting-a-new-Project-Type#implementing-a-new-project-type))
  * Also need `title` for project type
* Nitpicks (both in [new project type](https://github.com/Shopify/shopify-app-cli/wiki/Starting-a-new-Project-Type#implementing-a-new-project-type)):
  * Since the sample `create` command doesn't use `name`, it should be `_name`
  * Typo at the bottom of sample `cli.rb`, should be `:FooBuilder` instead of `:FooBulder`

**Comment by mkevinosullivan** [comment]
Updated/fixed
- [x] Prereq task loaded as string, should be a symbol (x)
- [x] Forms aren't loaded in cli.rb (x)
- [ ] Loading for creator in cli.rb is out of date, was changed in this PR (x) - _`v2` of CLI doesn't have `creator` anymore..._
  - [ ] Also need title for project type - _... nor does it use `title`_
- [x] Nitpicks (both in new project type):
  - [x] Since the sample create command doesn't use name, it should be _name
  - [x] Typo at the bottom of sample cli.rb, should be :FooBuilder instead of :FooBulder
