### ISSUE TITLE
You cannot publish a development theme.

### ISSUE THREAD

**Issue by trenkwill** [Shopify/shopify-cli#1350]
# Issue summary

Write a short description of the issue here ↓
When I'm on my development theme locally (http://127.0.0.1:9292) I cannot publish it to the closed development store. 
Same in the theme customizer when I click on the Publish button.

## Expected behavior

What do you think should happen?

Being able to publish the theme I'm working on

## Actual behavior

What actually happens?

 
When typing `shopify theme publish` in CLI I'm getting  `422 (ShopifyCli::API::APIRequestClientError)
{"errors":{"base":["You cannot publish a development theme."]}}`

**Comment by macournoyer** [comment]
Development stores a for local development only.

How did you try to publish the development theme (what exact command did you run)? The CLI shouldn't give you this option.

If you want to publish the files you have in your current directory, try: `shopify theme push --publish`

**Comment by trenkwill** [comment]
what is the difference between `shopify theme push --publish` and `shopify theme publish` ?

Also when make changes in the customizer and type `shopify theme push` I'm not seeing the changes I made in the live theme customizer. Is that normal?

**Comment by macournoyer** [comment]
`shopify theme push --publish` will push the local files, then publish the team to be the live one
`shopify theme publish`, only switches a remote theme to be the live one, no pushing of files involved.

Not sure what you mean by "theme customizer". Talking about the Theme Editor? What is the URL for this in your browser?

**Comment by trenkwill** [comment]
> Not sure what you mean by "theme customizer". Talking about the Theme Editor? What is the URL for this in your browser?

yes the theme Editor  

When I’m working locally and do changes in the theme editor then `shopify theme push`
none of the editor changes I did are pushed to the theme editor on the live theme.  
I have to redo them all over again :(

**Comment by macournoyer** [comment]
Oh I see! So you want to publish the editor changes you did on your development theme to the live one, correct? Is that the use case?

**Comment by trenkwill** [comment]
Yes exactly!!

**Comment by macournoyer** [comment]
You could `shopify theme pull` (it will overwrite your local files), to pull the `.json` files generated by the Editor. Then push everything to the live theme.

But this is not a fun workflow. I'll bring this up, and see if we can come up with something better. Thanks for reporting this!

**Comment by climbandfocus** [comment]
following, same issue.  not sure how to take my development theme and push it to the store

**Comment by nick-addison-applications** [comment]
We are seeing this issue as well when testing the Dawn theme.

When using the Shopify admin and going to Online Store > Customize Theme and making changes to the section/block settings, the user input is stored in the corresponding .json template file (this includes block and section order).

When running `shopify theme serve` with the cli, 
An output is given with a url to edit the theme settings:
https://{ merchant_url }/admin/themes/{local_theme_id}/editor

When using this url to make updates to the theme locally, no adjustments are made to the .json template file. 

The only place I could find the settings data was by using:
`console.log(document.getElementById('OnlineStoreEditorData').innerHTML);`
In the console on https://{ merchant_url }/admin/themes/{local_theme_id}/editor

However, this json is not the same format as the .json template files, so it cannot be directly copy and pasted.

**Comment by james0r** [comment]
> Development stores a for local development only.
> 
> How did you try to publish the development theme (what exact command did you run)? The CLI shouldn't give you this option.
> 
> If you want to publish the files you have in your current directory, try: `shopify theme push --publish`

This could really be made more clear in the docs. For older Shopify devs most likely many are scratching their heads about the limitations of development stores/themes. So in a development store it's impossible to publish a development theme? Am I understanding this correctly?

**Comment by serge512** [comment]
Hi, what i found is that you first need to push as unpublished then you can publish

`shopify theme push -u`

put a name, then pick the delevoment theme and done, be sure to pull with option -n like `shopify theme pull -n` that way it won't delete any file that is not being downloaded.

after working on it the theme can be published normally `shopify theme push -p`

**Comment by ckeim** [comment]
i've also found if I use `shopify theme push` it overwrites all of the dynamic sections a user has added from the published theme. Each time I use this command, I have to log back into my customizer and re-do all of the sections.  I've read through the new documentation and there's nothing about preserving data and settings through this development flow.

How can I prevent my settings getting overwritten?

**Comment by trenkwill** [comment]
Exactly, this is why I went back to themekit unfortunately

**Comment by andrclp** [comment]
> i've also found if I use `shopify theme push` it overwrites all of the dynamic sections a user has added from the published theme. Each time I use this command, I have to log back into my customizer and re-do all of the sections. I've read through the new documentation and there's nothing about preserving data and settings through this development flow.
> 
> How can I prevent my settings getting overwritten?

you can try shopify theme pull, pull the data from the theme that has been modified on the store, then push with all the changes

**Comment by jnicol** [comment]
> you can try shopify theme pull, pull the data from the theme that has been modified on the store, then push with all the changes

Works for me :) As @nick-addison-applications mentioned earlier in the thread, section customisations are stored in the corresponding template JSON file (in the settings key). Pulling will download those modified templates, and the settings will be preserved when you push later on.

**Comment by franko19** [comment]
> `shopify theme push --publish` will push the local files, then publish the team to be the live one
> `shopify theme publish`, only switches a remote theme to be the live one, no pushing of files involved.
> 
> Not sure what you mean by "theme customizer". Talking about the Theme Editor? What is the URL for this in your browser?

this workflow works for me, is a long process but it works. Thank you

**Comment by nayakayp** [comment]
> You could `shopify theme pull` (it will overwrite your local files), to pull the `.json` files generated by the Editor. Then push everything to the live theme.
> 
> But this is not a fun workflow. I'll bring this up, and see if we can come up with something better. Thanks for reporting this!

Hey thank you, this solve my synchronization problem between local version and live version
I think this workflow make us confused. Any update?

**Comment by benshrimpton** [comment]
Second this. It seems like most devs used to `theme watch` were expecting the data created inside of section to be written to `settings_data.json`, but they are in fact written to the individual `section-name.json` files. This is an absolute disaster workflow feature and should never have been released. I'm pretty sure there's hundreds of devs who keep seeing content vanish and live sites destroyed. The file structure that Shopify writes to these sections is also meaningless to merge with your Git workflow.  Shopify needs to abandon this ASAP, and start using a `database`

**Comment by trenkwill** [comment]
Absolutely! Thanks for pointing this out

**Comment by ADTC** [comment]
Everyone is suggesting here to do a `shopify theme pull` first and do `shopify theme push` after, assuming it pulls changes made on Shopify into your local development, merges them with your local changes, then pushes everything to Shopify. _(Here and in #1511.)_

### But it doesn't work that way! 🤷‍♂️

I can see where this thinking comes from. This is how Git works. Because Git tracks history, it can pull remote changes and merge them with local changes, creating a merge commit if necessary, then push everything to remote.

But Shopify CLI **blindly** erases all local changes when pulling remote changes! On the other hand, if you push local changes without pulling, it **blindly** erases remote changes - that's what happened to you @ckeim

## This is the correct workflow:

- First of all, set up a Git repository on your local theme and get in the habit of staging and committing changes. _(If you're new to Git, there are plenty of crash courses online!)_
- Shopify CLI has no knowledge of Git, so you must manually keep track of the last commit which you had pushed to Shopify using `shopify theme push`. **Ideally this should be the top-most commit of your main branch or your working branch.**
- If you made new changes in your local environment but suspect that your client or someone else made changes in Shopify theme customizer or Edit Code function (the remote), you must do the following:

1. Stash your changes into Git using `git stash`. This should bring the local theme back to the last state that you pushed to Shopify.
2. Use `shopify theme pull` to pull down all the remote changes. This will bring the local theme up to the current state of the remote theme in Shopify admin (including all those new sections your user made, @ckeim).
3. Use `git add --all` and `git commit` to make a commit of these remote changes. The message can be something like _"Pull remote changes"_.
4. Pop the Git stash using `git stash pop`. This will put back all your local changes on top of the new remote changes. **(Note that at this point, if you get merge conflicts, you must resolve them first before the next step.)**
5. Use `shopify theme push` to push up all the local changes to Shopify. This will bring the remote theme up to the current state of your local theme, and it will include all the remote changes of your users **and** your local changes.

One more thing, ideally you should work on your local theme when you're sure nobody is modifying the remote theme on Shopify admin. However, if you're working at a time when users are busying modifying the live theme, work on a duplicate copy of the theme instead, then use a similar procedure during off-peak hours to merge everything and push into the live theme.

_PS: I'm on Shopify CLI version 2.3.0. Personally I think it's ridiculous that we have to do such a convoluted workflow. I wish Shopify CLI was intelligently designed to automatically merge changes, or at least be Git-aware._

**Comment by ADTC** [comment]
@trenkwill the above procedure will pull those changes as well, because they are recorded automatically in the JSON files (used to be only in `settings_data.json` but in OS 2.0, it appears to be in dedicated JSON files as well).

Anything that you do through Shopify Admin (which affects theme files) can be considered as "remote changes" in the above instructions.

Yes, there is no easy way to sync the content, but by carefully following the above, you'll avoid losing your work.

**Comment by jnicol** [comment]
@ADTC The git workflow you suggest (stashing and merging changes) is great protection against accidentally losing local changes, so thanks for detailing it here :) Regardless of the workflow one follows, I think it is imperative to keep the theme under version control, and never ever perform a pull without first committing any changes!

> Everyone is suggesting here to do a `shopify theme pull` first and do `shopify theme push` after, assuming it pulls changes made on Shopify into your local development, merges them with your local changes, then pushes everything to Shopify.

It was never my impression that `shopify theme pull` merges changes. I understand that it overwrites everything, `--ignore` (introduced in CLI 2.3.30) notwithstanding. The push/pull workflow suggested in this thread depends on the developer not making any changes locally until after they have pulled, since pulling will wipe out their local copy of the theme. It's a horrible workflow, but it's workable if one understands its limitations.

But ultimately this whole mess comes down to poor design decisions on Shopify's part. As @benshrimpton pointed out, section data should never have been stored on theme .json files. It belongs in a database, like product data, page data etc.

**Comment by ADTC** [comment]
@jnicol I think you mean `-n` or `--no-delete` as I can't find any _`--ignore`_. I'm not sure how it can help, as it only says _"Runs the pull command without deleting local files."_ which I assume means that it will still overwrite changes, but just won't delete local files that don't exist in the remote side.

**Comment by jnicol** [comment]
@ADTC https://github.com/Shopify/shopify-cli/pull/1479

**Comment by jroyprevost-gorillagroup** [comment]
@macournoyer You're saying a development store is for local environment only. Can't it be used to create a dev/stage sandbox to have QA and developers all look at the common store? In that case would we publish our custom theme to a development store or is there a preferred approach to have a safe place that's separate from prod?

**Comment by owenfranssen** [comment]
Horrendous workflow aside. Is there a way to  only pull selected files?
I see you can specifiy files to --ignore, but nothing about selectively pulling

**Comment by macournoyer** [comment]
@jroyprevost-gorillagroup you could push to an unpublished theme for this `shopify theme push -u`. That will be behave close to how the GitHub integration works too. The problem with development themes is that they will be deleted after a period of inactivity. Is the issue that you don't want to the theme to appear in the Admin dashboard?

@owenfranssen I feel what's missing is the inverse of `--ignore`, maybe `--only`? Got a better name?

**Comment by benshrimpton** [comment]
@bantros To add another breaking workflow feature: The new GITHUB integration is great, you add a theme from a Git repo. The problem is, you can only add it once, so if the store admin duplicates the theme, you immediately break the Git connection. Never in the history of a Shopify store has the admin not duplicated the theme, as that's the only sort of the workflow possible to stage new content before publishing.

**Comment by owenfranssen** [comment]
About to experiment with this, but one of the recent updates to the CLI tool added the [`--theme-editor-sync` flag](https://shopify.dev/themes/tools/cli/theme-commands#optional-parameters) to `shopify theme serve` which claims to sync settings both ways
