### ISSUE TITLE
Undefined filter metafield_tag

### ISSUE THREAD

**Issue by javimata** [Shopify/shopify-cli#1356]
Write a short description of the issue here ↓

I use this filter to display a metafield but i receive this msg
Undefined filter `metafield_tag`
I see this filter in https://shopify.dev/api/liquid/filters/metafield-filters

this is my code 
{% assign meta = product.metafields[namespace][key] %}
{{ meta | metafield_tag }}

i use v2.0.2

**Comment by nresh** [comment]
@javimata I'm new to shopify/liquid (literally started looking at it today) - but i suspect the issue is you're having has to do with how you're defining `meta`.

I think the error you're seeing is caused by `meta` not being a valid `metafield` object (and so it doesn't have an associated `metafield_tag` filter).  this is happening probably because of how you're trying to retrieve it with square brackets.

according to https://shopify.dev/api/liquid/objects/metafield#direct-access:
> you can't loop over a namespace to get each individual metafield

I can't tell based on what you sent, but it looks like your code may be part of a loop? even if it isn't, I'd try to directly add your meta tags like so (assuming you have a namespace called `namespaceA` and there is a key called `key1`):
```
{% assign meta = product.metafields.namespaceA.key1 %}
{{ meta | metafield_tag }}
```

**Comment by perryraskin** [comment]
I'm having the same issue, it's not in a loop. I have it in a template JSON file.

```
"settings": {
            "heading": "Size",
            "content": "<p>{{ product.metafields.my_fields.length | metafield_tag }}</p>",
            "page": "",
            "icon": "ruler"
          }
```

Interestingly enough, this error only seems to occur when I'm trying to run the theme locally using `shopify theme serve`. This theme is also duplicated as one of the theme drafts, which does not have these errors and displays the correct theme preview.

**Comment by nresh** [comment]
@perryraskin just to be clear, `my_fields` is a namespace and `length` is one of the keys in the namespace?  the reason I ask is `.length` seems like a bad choice for a key, since it can easily be confused with trying to get the length of an array (I'm not sure if liquid accepts `.length` but that would be my first thought).

that being said, one other piece of documentation I found on https://shopify.dev/api/liquid/objects/metafield:
>Metafields of type integer, json_string, and string are older implementations that don't have the following attributes, and aren't compatible with metafield filters. To learn more, refer to Deprecated metafields.

here is a list of accepted types: https://shopify.dev/apps/metafields/definitions/types

I'm wondering if you have an incompatible `type` for your metafield and so the filter doesn't work.  perhaps your local theme is running on a newer version of liquid in which your metafield types are no longer compatible.

**Comment by perryraskin** [comment]
I'm still getting used to the new Shopify CLI and it seems I made a mistake and I was logged into the wrong store (via the CLI). It was an older store, so yes, you are partially correct there!

Though unfortunately I get the "We'll be back soon!" error page from Shopify when I try to access the local server of the theme. That's a different issue, but it's weird. It takes me to the "enter password" page to access the site, then I authenticate by logging in, and then error page.

**Comment by javimata** [comment]
I don't know about the others, but I see my error in Theme Check, the code works fine, but I get that notification

**Comment by roark** [comment]
I'm also experiencing this issue when trying to use in **App Embed Block** liquid code. When I do an `shopify extension push` I recieve the error:
```
✗ Undefined filter `metafield_tag` at snippets/extension.liquid
```
I also recieve a similar error when using some other newer liquid statements such as `metafield_text` and `remove_last`. 

Any idea how we can overcome this, maybe a force push?
Is this an issue with Shopify servers rejecting liquid code based on an old schema of valid statements?

At the moment, I'm unable to deploy using these statements and have to reimplement them manually to covert over to App Embed Blocks.
