### ISSUE TITLE
Font unrecognized on local development server

### ISSUE THREAD

**Issue by perryraskin** [Shopify/shopify-cli#1370]
# Issue summary

I'm using the CLI for the first time, and all is going well on the local dev server, but the main font (Cooper BT) does not seem to be loading. It loads just fine in any theme preview, but not on the local server. 

I installed the font on my Mac but the name is slightly different. Either way I would assume one of the fallback fonts would kick in?

I'm working with Edge browser if that helps. See screenshot below for side-by-side of theme preview and the local preview. Both are previews of the same exact theme, just one is the live preview, and one is the dev server.

<img width="2341" alt="Screen Shot 2021-07-12 at 4 17 32 PM" src="https://user-images.githubusercontent.com/17967465/125350647-0614ec00-e32d-11eb-9f83-28ebe5b029f7.png">

**Comment by m-allanson** [comment]
I'm seeing the same issue. This happens for custom fonts chosen through the Theme Editor. 

The fonts load correctly when viewed on the development store _example.myshopify.com_. They don't load when viewing locally via _http://127.0.0.1:9292/_.

The requests for the font files are being rejected with _406 Not Acceptable_. 

If the CLI is working as a proxy, I guess the requests are failing due to the HMAC parameter only being valid for requests with an _origin_ of _example.myshopify.com_?

Here's an example request:

```
curl 'https://fonts.shopifycdn.com/sabon_next/sabonnext_n4.017b46b69ae2f6cc21583365a3b12e50f5975c21.woff2?&hmac=df2ef4cb83047784740753d9fa8c2c1869a1d07dd94a6f5f039f602cfce325cb' \
  -H 'authority: fonts.shopifycdn.com' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: "Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"' \
  -H 'origin: http://127.0.0.1:9292' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4581.0 Safari/537.36' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'accept: */*' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: font' \
  -H 'referer: http://127.0.0.1:9292/' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  --compressed  
```

And a screenshot of the response from Chrome's dev tools:

<img width="800" alt="Screenshot 2021-07-22 at 14 19 19" src="https://user-images.githubusercontent.com/381801/126646328-e074ac79-6848-4eff-9415-32bec1b4f74a.png">

**Comment by macournoyer** [comment]
Closing as duplicate of #1533
