### ISSUE TITLE
rails create fails because of ruby version mismatch

### ISSUE THREAD

**Issue by attaboy** [Shopify/shopify-cli#1414]
I tried running `shopify rails create`, and the command didn't complete successfully because of a Ruby version mismatch. It failed after the bundle step, seemingly at `rails webpacker:install`.

I have ruby 2.6.7 installed, which makes the error all the more confusing because it says "Your ruby version is 2.6.3".

```
┃ Bundle complete! 15 Gemfile dependencies, 71 gems now installed.
┃ Use `bundle info [gemname]` to see where a bundled gem is installed.
┃          run  bundle binstubs bundler
┃        rails  webpacker:install
┃ /usr/local/Cellar/shopify-cli/2.1.0/gems/bundler-2.2.24/lib/bundler/definition.rb:455:in `validate_ruby!': Your Ruby version is 2.6.3, but your Gemfile specified 2.6.7 (Bundler::RubyVersionMismatch)
┃ 	from /usr/local/Cellar/shopify-cli/2.1.0/gems/bundler-2.2.24/lib/bundler/definition.rb:430:in `validate_runtime!'
┃ 	from /usr/local/Cellar/shopify-cli/2.1.0/gems/bundler-2.2.24/lib/bundler.rb:143:in `setup'
┃ 	from /usr/local/Cellar/shopify-cli/2.1.0/gems/bundler-2.2.24/lib/bundler/setup.rb:20:in `block in <top (required)>'
┃ 	from /usr/local/Cellar/shopify-cli/2.1.0/gems/bundler-2.2.24/lib/bundler/ui/shell.rb:136:in `with_level'
┃ 	from /usr/local/Cellar/shopify-cli/2.1.0/gems/bundler-2.2.24/lib/bundler/ui/shell.rb:88:in `silence'
┃ 	from /usr/local/Cellar/shopify-cli/2.1.0/gems/bundler-2.2.24/lib/bundler/setup.rb:20:in `<top (required)>'
┃ 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
┃ 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
┃ 	from /Users/lukeandrews/src/rails_app_july_2021/config/boot.rb:3:in `<top (required)>'
┃ 	from bin/rails:3:in `require_relative'
┃ 	from bin/rails:3:in `<main>'
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (185.74s) ━━
✗ System call failed: /usr/local/Cellar/shopify-cli/2.1.0/bin/rails new --skip-spring --database=sqlite3 rails_app_july_2021
```

**Comment by cefigueiredo** [comment]
I had this issue as well.
The `shopify-cli` installed from homebrew is using System's ruby instead of the ruby from my version manager (RVM) or even from the ruby version installed by homebrew (homebrew identify ruby as a dependency and install it).

On my case, I use rvm as ruby version manager, and had it set to use ruby-3.0.0.
Homebrew also installed a ruby-3.0 that it used to run `rails new` stuff, but on this part to run `rails webpacker:install` it seems to use OSX's ruby for some reason, that on my case is 2.6.3 as well.

The solution for me was uninstall shopify-cli from homebrew, and install the **gem** shopify-cli instead

That installs shopify-cli on the RVM structure, so I have more control over the ruby version.

The binstubs for `shopify` were created normally on `/usr/local/bin/` and pointed to RVM's exact ruby version.
```
carlos ~/dev $ rvm current
ruby-3.0.0
carlos ~/dev $ which shopify
/usr/local/bin/shopify
carlos ~/dev $ cat /usr/local/bin/shopify
#!/usr/bin/env bash
/Users/carlos/.rvm/rubies/ruby-3.0.0/bin/ruby -I /Users/carlos/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.1.0 /Users/carlos/.rvm/gems/ruby-3.0.0/gems/shopify-cli-2.1.0/bin/shopify $@
```

After that, run `shopify rails create` runs flawless for me.

**Comment by cfxd** [comment]
> Jasons-iMac-2:~ jason$ rbenv global 3.1.0 Jasons-iMac-2:~ jason$ rbenv version 3.1.0 (set by /Users/jason/.rbenv/version)
> 
> But still getting this error.

I'm having the exact same issue with `shopify-cli` and `rbenv`. @jason3w did you ever resolve this?
