### ISSUE TITLE
Shopify CLI Store Editor (Store Customizer) not transferring work on "shopify theme push" command

### ISSUE THREAD

**Issue by taylorsundali** [Shopify/shopify-cli#1511]
# Issue summary
I worked on a Shopify theme for several hours via the shopify CLI. This was using the command "shopify theme serve". After using that command, the terminal spit out a preview link, and a link to use for the theme editor / customizer. A combination of changes to theme files via liquid / HTML / CSS and edits in the editor / customizer (more in the eiditor / customizer than anything). When I went to run "shopify theme push" I had built out a new home page. The changes I made to theme files transferred via "shopify theme push", but _none_ of the work in the theme editor / customizer transitioned. This effectively lost 3 hours of work. 

## Expected behavior
I expected that all changes I had made via the theme editor spit out by the terminal using "shopify theme serve", which should be building out changes in the config/settings_data.json file, would have transferred to the online store.

## Actual behavior
None of these changes transitioned. I lost all changes made in the theme editor

## Steps to reproduce the problem
1. Open terminal and navigate to a file with shopify theme files. Or, create a new folder and use shopify theme pull to get files from a theme into your local. 
2. run "shopify theme serve" in your terminal. 
3. Make a change using the Online Store Editor link they provide. Save the change. 
4. Stop serving the shopify theme. 
5. Use "shopify theme push" to push the changes from the local to the remote. Make sure to overwrite a theme you don't care about. 
6. Preview the theme on the shopify remote that you just overwrote. The change you made will NOT be there. 

## Specifications
- App type: Shopify
- Operating System: Mac OS Big Sur Version 11.5.2
- Shell: Terminal
- Ruby version (ruby -v): 2.6.3p62

**Comment by ADTC** [comment]
@AlexEmery are you sure about what you said? When I did `shopify theme pull` it erased my local changes. Thankfully I had done a `git diff` on the Terminal before this and I was able to copy and redo the changes from the diff output. Since I was burned once, now my procedure is to always check for local changes, commit or stash them in Git, make sure the working directory is clean, and only then execute `shopify theme pull`.

I came here looking to see if there's an issue asking for enhancement on this regard, so that the pull action is intelligent to recognize and merge changes, or at least stash the local changes to the available Git repo automatically (or warn if there's no Git repo).

@taylorsundali I highly recommend adding Git to your workflow, and making sure to track and commit all your changes before doing `shopify theme pull/push`. 🙂
