### ISSUE TITLE
package.json deleted on pull, not respecting .shopifyignore

### ISSUE THREAD

**Issue by bigskillet** [Shopify/shopify-cli#1518]
# Issue summary
`package.json` file is being deleted on `shopify theme pull`, even if added to `.shopifyignore`.

## Expected behavior
`package.json` file should be ignored and respect `.shopifyignore` file.

## Actual behavior
`shopify theme pull` deletes `package.json`.

**Comment by jstukey** [comment]
same here

**Comment by matt-cos** [comment]
I'm having this issue as well

**Comment by pinguluk** [comment]
+1

**Comment by nireno** [comment]
> +1 Until it's fixed, you can use the `--nodelete` flag: `shopify theme pull --nodelete`

Just be aware that this can cause subtle problems for example in my case, the changes that were being pulled were for what I believe is now called shopify 2.0 in which it was necessary for a JSON file eg 404.json to replace an existing liquid file. But  because no delete was turned on the old liquid files weren't being properly removed which caused my development theme to render differently from the live version which had me confused for quite a while.

**Comment by bigskillet** [comment]
Ping
