### ISSUE TITLE
[Major Feature] Built-in Git-awareness of Shopify CLI to curb overwriting theme files and losing work

### ISSUE THREAD

**Issue by ADTC** [Shopify/shopify-cli#1682]
Making Shopify CLI a **Git-aware application** will boost its utility as a developer tool, especially for developers who are using `theme pull` and `theme push` on a regular basis. I briefly touched on the lack of Git-awareness in https://github.com/Shopify/shopify-cli/issues/1350#issuecomment-923068012 and https://github.com/Shopify/shopify-cli/issues/1350#issuecomment-925784575

I believe it will solve a lot of problems and frustrations reported often here, related to loss of work caused by how `theme pull` and `theme push` currently works, and lead to a smoother, more efficient workflow when using Shopify CLI. Please consider building this feature to make the CLI aware of the presence of a Git repository.

- [ ] Warn CLI users of the absence of a Git repository during the use of critical `theme` commands.
- [ ] Stash local changes and re-apply them when using `theme pull`. This could be an option, and if not enabled, warn and ask permission to overwrite local changes. _(Merge conflicts can occur - Git will guide the users on resolving them.)_
- [ ] Tag the `HEAD` commit with theme ID and name when using `theme push` (if there are no uncommitted changes).
- [ ] Commit any uncommitted changes and tag it (as said above). Or warn and ask permission to push if the changes are uncommitted.
- [ ] Check the last-committed version of the theme (based on tags) to see if theme diverged on Shopify on `theme push`. Warn and ask permission to overwrite remote (default to "no" and suggest pulling the theme to merge first).
- [ ] Show `git status` output automatically where appropriate; for example, after pulling theme from Shopify.
- [ ] Automatically maintain a section in `.gitignore` to exclude the corresponding `.x` file for each individual `.x.liquid` file in the `assets` folder (where `x` can be any file extension).

Note that some of these could be optional and perhaps configurable in a `shopify-cli.config` file _(or another name)_ in the project (checked into the repo) or globally in the user's home folder.

_If you can think of other Git-related features that could be useful if implemented in Shopify CLI, please comment and I'll add them._

**Comment by macournoyer** [comment]
Thinking more about this, have you tried our [GitHub Integration](https://shopify.dev/themes/tools/github)?

`theme pull` & `theme push` were build as an non-git alternative to this.

Technically if you're using the GitHub integration, you shouldn't need `theme pull` & `theme push`. As you'd use `git push` & `git pull` instead.

I know you have to use `theme pull` now to get changes from the Editor, but that's why I think we could solve this one use case with #1708.

Perhaps we could just add a confirmation step before overriding local files with `theme pull` to avoid accidentally overwriting files?

**Comment by brightonmike** [comment]
https://github.com/Shopify/shopify-cli/issues/1682#issuecomment-965311671

Just want to add some feedback to this - I've been through so much pain developing a theme because I didn't know this integration existed until I found this thread, and I could see no end to problems of data loss caused by `theme pull` and `theme push`. Sure, there's flags to ignore files, but it becomes tricky to manage the process between folks making content changes and folks making dev changes. It's a perilous process as all it takes is one accidental push without a pull first and a whole raft of changes can be lost.

If the integration is the solution, I feel the CLI tool should really be pointing developers in that direction. Even just a small message to a) warn of possible content data loss and b) suggest the dev uses the integration to avoid any content loss.

There is also nothing in the documentation to warn you of this behaviour https://shopify.dev/themes/tools/cli/theme-commands#push

**Comment by ADTC** [comment]
@brightonmike it's annoying, isn't it?! Because of this, I've been extra careful with Shopify CLI:
* Always have a Git repository on your theme.
* Stash or commit your changes and return your working tree to the last known commit which you pushed to Shopify (yes, you have to manually track this somehow).
* Pull the theme to a clean working tree and check if the tree became dirty. If yes, then commit those changes separately and merge them to your local changes.
* Push only after you did the above (to ensure you don't lose changes in Shopify side).
* Avoid pushing uncommitted changes to Shopify. Always commit to Git first.

**Comment by ADTC** [comment]
This is still very much relevant...

**Comment by ADTC** [comment]
Can we still discuss this? Erasing data without consent or warning is a big no-no.

**Comment by ADTC** [comment]
Gah! How can we make this unclosable by the bot? This is in no way "completed" and still a major problem.

**Comment by Elliottmeija** [comment]
Yeah, it's terrible, but this isn't an easy fix, and if GNOME's thumbnail
bug fix took 15 years (!!!) there's some operational precedent here. I
think the best way to keep this issue open is to file reports every time it
happens and mention how much work you are losing.

**Comment by ADTC** [comment]
Well, it's already closed so we have to create a new one.
