### ISSUE TITLE
CLI App is borked

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify-cli#1834]
# Issue summary

Login to my partner account, and login to a development store I just made. Tried to populate it with products, Shopify CLI exits saying that command is not allowed. 

## Expected behavior

Shopify CLI should populate my development store with products. 

## Actual behavior

Command errors out for some bizarro reason.

<details>
shopify populate products
✗ Command not allowed with current login. Please check your login details with shopify whoami. You may need to request additional permissions for this action.
</details>

## Steps to reproduce the problem

1. login to store with my partner account
2. use the populate command

## Specifications

- App type:
- Operating System: Mac OS
- Shell: iterm
- Ruby version (ruby -v):  3.0.3
- Shopify CLI: 2.7.2

**Comment by TheApeMachine** [comment]
You need to make a staff account in your dev store settings (so that is the settings in your store, not in the partner accoutn) with the same email. You have to accept the email it sends you too.

**Comment by resistorsoftware** [comment]
Wow. OK. So that is so counter-intuitive it is almost, but not quite, crazy. I tried it, and it does not work though, so sadly I have to write this off too. When I add myself with the same email as a staff account, and send the invite, the invite never arrives, telling me something internal at Shopify does not want this to happen.

**Comment by TheApeMachine** [comment]
Ah, and I gave my staff account all rights, could be something good to know.

**Comment by TheApeMachine** [comment]
Hmmm, and this is definitely a long shot, but I saw other people complaining about something else who were also running Ruby 3, whereas I am running a 2 version still.

**Comment by resistorsoftware** [comment]
No, it is not like Shopify sent the email to spam. There is simply no record of Shopify having sent the email at all. And yes, I gave myself all access to the staff account. 

So once again, this is an issue internal to Shopify, and not just with the CLI tool, but with their tooling of how partner and developer accounts work. 

I hope 2022 is kind to us, and that their team of noobs figure out all these small niggling issues, allowing external developers to function at a higher level than is currently supported. Which of course, since it is borked, would be an order of magnitude improvement!

**Comment by resistorsoftware** [comment]
> 

It is possible this has to do with Ruby 3. There are indeed some things that work better when you fall back to 2.7. I am not going to opine on that. If Ruby 3 truly is a problem for Shopify, I am shocked. Their monolith running a bazillion transactions a second, is on Ruby 3 just fine, so these tiny little developer tools in comparison should also work fine on Ruby 3. It is not like that is a major hoop for anyone to jump through.

**Comment by TheApeMachine** [comment]
Really I am not sure, I just happened onto this stuff because of a new job. My experience with Shopify development is about two weeks long. The cli improves on my life, believe me :p It's either that or read someone's insane readme where every step is slightly more insane then the previous one. The whole thing does work in Docker too, just needed to discover some undocumented ENV settings. But yeah, don't know what to tell you about the mail, I tried twice, it worked, sorry... Not sure if there is a way to activate the account otherwise?

**Comment by TheApeMachine** [comment]
So the people who set this up did not follow instructions very well, so it took me 2 days to figure out how to run it, and then there were even more quirks down the road. The docker (and compose) setup makes it so that 1. The next developer and the ones after that will not have to go through the same, and 2. I can deploy it easily to Kubernetes.

**Comment by TheApeMachine** [comment]
Ah no, the tool is just one element :p You don't just use the tool, you use the tool to provision your shop/app/etc

**Comment by resistorsoftware** [comment]
I still have no clue why you'd need Kubernetes. From my reading of that tech, no one needs Kubernetes except companies like Google where they have the money to devote to supporting such complex overkill. How would a developer working on Shopify ever need Kubernetes? Can you tell me some good examples so I can hear from someone that has real world experience in how it pays off? Some people think Docker is complex, and it is 1000x easier to deal with than Kubernetes from what I hear.

**Comment by TheApeMachine** [comment]
Kubernetes is difficult to learn sure, but I have made all my configs and done the hard work, so my clusters, whenever I need one, deploy straight out of git, hardly any effort needed since I also have the OS install and initial node(s) setups automated. And who says I am limited only to Shopify development? That is just a single part in a much larger stack. Besides that, it brings me multiple environments, so, development, staging, QA, production. And the fault-tolerance is not such a bad thing either. Then, let's see, well, it just also really really fun to work with, especially when you get to the API part in Go, which effectively allows me to use both Docker and Kubernetes straight from code. But we're straying off-topic here :)

**Comment by resistorsoftware** [comment]
Right. There is a close to zero chance Kubernetes would ever save a developer any time or effort when faced with simply making a **shopify login** call to their partner account. One can do as they wish with regards to their digital choices.
