### ISSUE TITLE
Question: How do I "watch and upload" for changes while developing locally?

### ISSUE THREAD

**Issue by ManasN** [Shopify/shopify-cli#1942]
I would like an "theme watch" equivalent. How to achieve the same using OS2 Shopify themes?

**Comment by lesterdefreitas** [comment]
@ManasN The simple answer to your question is that `shopify theme serve` is essentially a `theme watch` equivalent, only that it watches a development theme that is generated on the fly and viewed locally rather than one of the existing themes on the storefront.

 If I understand the decision to move from `theme watch` with themekit to `shopify theme serve` with shopify cli correctly, this probably means that the cli will never have a theme watch functionality the same as what themekit had. The reason for this, as I understand it, is that `theme watch` will overwrite files on the theme with your local files, potentially losing changes made to the theme on Shopify. Whereas `shopify theme serve` overwrites nothing, and instead generates a new development theme based on your local files.

**Comment by ManasN** [comment]
> @ManasN The simple answer to your question is that `shopify theme serve` is essentially a `theme watch` equivalent, only that it watches a development theme that is generated on the fly and viewed locally rather than one of the existing themes on the storefront.
> 
> If I understand the decision to move from `theme watch` with themekit to `shopify theme serve` with shopify cli correctly, this probably means that the cli will never have a theme watch functionality the same as what themekit had. The reason for this, as I understand it, is that `theme watch` will overwrite files on the theme with your local files, potentially losing changes made to the theme on Shopify. Whereas `shopify theme serve` overwrites nothing, and instead generates a new development theme based on your local files.

Thank you. I was finding manually "pulling" and "pushing" theme files a bit tedious hence the reason of this post. Currently my workflow is like this:
1. Have a production theme (published)
2. Have a staging theme (unpublished)
3. "Pull" staging theme, make changes. Now with CLI, those changes get written to a temporary development theme.
4. If there are any changes to be made using Shopify's editor, make those changes on the temporary development theme.
5. Again "Pull" the development theme to local staging
6. "Push" development theme to staging theme

I would've loved an option where I can just "watch" for changes in my staging theme and have them uploaded to Shopify as I develop. Please suggest me if you have a more optimum workflow

**Comment by lesterdefreitas** [comment]
@ManasN I am by no means highly experienced when it comes to development workflows, but what we do is this:

- For new development work we use a development theme and we work in a new development branch on git
- We have our staging theme copy on the store as well, that is connected to a staging branch on git via the Shopify x Github integration
- When we are done with development, we merge our dev branch into the staging branch, which then sync the updates to the staging theme on Shopify for the client to view
- Once the development is approved, we merge to the main branch on git, which is connected to the published/live theme on the Shopify store.

Hope this helps.
