### ISSUE TITLE
Shopify CLI seems to be very sensitive about directories.

### ISSUE THREAD

**Issue by polidario** [Shopify/shopify-cli#1957]
# Issue summary

Shopify CLI seems to be very sensitive about directories.

For example, I have the following directory "C:/Users/Bernard Polidario/Projects" As you can see, there is a space in that directory.

If I run the command, `shopify app create php`

The CLI will clone the PHP app, but when it starts installing dependencies, it started causing issues like:
<details>**Unable to install all (number) of dependencies**</details>

I'll also attach a screenshot below.

![image](https://user-images.githubusercontent.com/71621723/150631045-0bf5b493-3451-4a8f-aee2-d5c0c87ba289.png)

Now, I've tried using composer to create a laravel project, and it's working. It installs all the dependencies, etc.

I've also tried making the Shopify app in a different directory like "C:/Projects" and it's working.

![image](https://user-images.githubusercontent.com/71621723/150631067-fe552da7-14cf-4eb2-8826-9d9d6d4423ed.png)

So, I'm guessing this is a Shopify CLI-related issue? Though feel free to correct me.

## Expected behavior

Shopify CLI should create the apps regardless of the directory name.

## Steps to reproduce the problem

1. Run `shopify app create php` on a directory with a space

**Comment by amcaplan** [comment]
Hi @polidario, thanks for opening the issue!

I managed to reproduce. Running the steps manually, it seems to be a complaint from artisan.

<img width="1370" alt="Screen Shot 2022-02-07 at 23 49 30" src="https://user-images.githubusercontent.com/6288426/152877804-2399ad46-0f5f-4369-82bf-43dcc2e20ea8.png">

@paulomarg correct me if I'm wrong, but it seems like this is a limitation of our dependency and it would be non-trivial to fix this?

**Comment by paulomarg** [comment]
I did some digging into this, and I think the problem is in how we create the app env file - when setting up an app, we use the app path to create the SQLite database file, and add it to the env under `DB_DATABASE`, which will in these cases contain whitespaces.

When we write that env to the `.env` file, we might not be adding quotes around it, which then causes the error above. Would it be possible to change env file writing to make sure this value gets quoted? We could do it from the command, but it might make sense to make this a bit more generic, what do you think?
