### ISSUE TITLE
[Feature]: <prevent pushing to live>

### ISSUE THREAD

**Issue by jo-elbdev** [Shopify/shopify-cli#2026]
### What type of project(s) will this request affect?

theme

### What type of change do you want to see?

Substantial change to existing feature

### Overview

It would be great if the default `shopify theme push` command would prevent the user from pushing into the live theme.

### Motivation

Developers quiet often accidentally push their themes into live themes.

**Comment by karreiro** [comment]
Thanks for reporting this, @jo-elbdev! 🚀

Currently, the CLI should ask for confirmation when users [push-and-select the live theme](https://user-images.githubusercontent.com/1079279/155965754-5c760eef-3b1a-458c-9cee-c01bbf31ead2.gif) and when [they use the `-t` flag](https://user-images.githubusercontent.com/1079279/155965723-0d5e9a3d-bea9-4d1d-9898-3fb18f90ddac.gif).

However, it doesn't ask with the `--live` (`-l`) flag. As we've received the feedback that running `shopify theme push --live --allow-live` would be a bit redundant (#1807).

Could you please share the flags you're using with the `shopify theme push` command? :)
(if you're not using `--live`, the CLI ***should*** be asking for a confirmation, so it's a bug)

**Comment by karreiro** [comment]
Thanks for reporting this, @jo-elbdev! 🚀
(I've deleted my other comment because it had an incorrect detail).

Currently, the CLI ***should*** ask for confirmation when users [push-and-select the live theme](https://user-images.githubusercontent.com/1079279/155965754-5c760eef-3b1a-458c-9cee-c01bbf31ead2.gif), when [they use the `-t` flag](https://user-images.githubusercontent.com/1079279/155965723-0d5e9a3d-bea9-4d1d-9898-3fb18f90ddac.gif), and even when they use the `--live` (`-l`) flag.

So, the CLI ***should*** be asking for confirmation. Could you please share the flags you're using with the `shopify theme push` command? :)
