### ISSUE TITLE
[Bug]: NoMethodError: undefined method `map' for nil:NilClass when trying to connect an extension (shopify extension connect) 

### ISSUE THREAD

**Issue by Jonida** [Shopify/shopify-cli#2234]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

Pushing a new version of a theme app extension should be successful via Shopify CLI, using the latest version of CLI and Ruby. 

### Actual behavior

An error shows once the command **shopify extension connect** is run. The errors points a ruby file and it also shows that there is no extension of this type. 

### Stack trace

```shell
PS C:\Users\..\shopify_extensions\gdpr\theme-app-extension> shopify version
2.15.3
PS C:\Users\Grisho\Desktop\shopify_extensions\gdpr\theme-app-extension> shopify login
√ Initiating authentication
√ Finalizing authentication
√ Loading available partner organizations
Logged into partner organization iSenseLabs
PS C:\Users\..\shopify_extensions\gdpr\theme-app-extension> shopify extension connect
X Loading your extensions…
┏━━ Task Failed: Loading your extensions… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ NoMethodError: undefined method `map' for nil:NilClass
┃
┃           app["extensionRegistrations"].map do |registration|
┃                                        ^^^^
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/lib/project_types/extension/tasks/get_extensions.rb:24:in `block in extensions_owned_by_organization'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/lib/project_types/extension/tasks/get_extensions.rb:23:in `each'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/lib/project_types/extension/tasks/get_extensions.rb:23:in `flat_map'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/lib/project_types/extension/tasks/get_extensions.rb:23:in `extensions_owned_by_organization'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/lib/project_types/extension/tasks/get_extensions.rb:16:in `block in extensions_from_organizations'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/lib/project_types/extension/tasks/get_extensions.rb:15:in `each'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/lib/project_types/extension/tasks/get_extensions.rb:15:in `flat_map'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/lib/project_types/extension/tasks/get_extensions.rb:15:in `extensions_from_organizations'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/lib/project_types/extension/tasks/get_extensions.rb:9:in `call'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/lib/shopify_cli/task.rb:8:in `call'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/lib/project_types/extension/forms/questions/ask_registration.rb:41:in `block in load_registrations'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:137:in `block in run'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:92:in `with_stdin_masked'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:125:in `run'
┃       from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/shopify-cli-2.15.3/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:48:in `block in initialize'
┣━━ STDOUT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ (empty)
┣━━ STDERR ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ (empty)
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (2.54s) ━━━
X You don't have any extensions of type theme_app_extension
* Learn more about building extensions at <https://shopify.dev/concepts/apps>, or try creating a new extension using shopify extension create.
shopify extension connect: Connects an existing extension to Shopify CLI. Creates a config file.
  Usage: shopify extension connect
```

### Reproduction steps

1. `shopify login`
2.` shopify extension connect`

### Operating System

Windows 10

### CLI version (run `shopify version` if you're not sure)

2.5.13

### Ruby version (run `ruby -v` if you're not sure)

3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]

**Comment by campmedia** [comment]
I'm having the same issue on my end.

**Comment by Jonida** [comment]
@campmedia Please check https://github.com/Shopify/shopify-cli/issues/2147#issuecomment-1094838029

**Comment by campmedia** [comment]
@kopcion This directory doesn't exist in my setup...
@Jonida This still pushed yes, but does not allow me to 'connect' to my dev extension. I have to go into my .env file and change the `EXTENSION_ID=` to the app I want to 'push' to.

**Comment by conspireagency** [comment]
@hannachen running into this issue as well with an existing app that 100% has a live theme app extension associated.  Have an extension ID in the .env file that corresponds to the existing extension

I modified the "get_extensions.rb" file ~line 22 to output what it finds.  I can see it iterates through every app under my partner account, however the output varies widely depending on the app.

For the app in question it shows nothing related to extensions, not even an empty array. Granted it has one and won't let me register a new one. However on other apps, notably those without extensions it shows an empty extensions registrations array such as:

 "extensionRegistrations"=>[]"

Just for the hell of it I "created" a new app extension an associated with some random app under my partner account that wasn't using a theme app extension.  This one showed the full extension information as expected ie:

"extensionRegistrations"=>[{"id"=>"4319117", "type"=>"THEME_APP_EXTENSION", "uuid"=>"3e0716b9-7a44-40f7-90c8-3e9bb8d42e21", "title"=>"theme-app-extension", "draftVersion"=>{"registrationId"=>"4319117", "context"=>nil, "lastUserInteractionAt"=>"2022-04-12T20:58:14-04:00", "location"=>"https://partners.shopify.com/xxxxxx/apps/xxxxxxx/extensions/theme_app_extension/xxxxxxx", "validationErrors"=>[], "id"=>"11424077", "uuid"=>"59c0fbca-d618-4bf7-aa19-9715376ea7cd", "versionTag"=>"0.0.0"}}]}

Bit frustrating since pushing / connecting doesn't work and you can't delete an app extension to attempt to register another one in its place.

**Comment by kopcion** [comment]
@hannachen if my understanding is correct the problem is how ruby handles concurrent http request, in certain ruby version they can't be simply run in multiple threads and that is what is causing the app extension to not load, filling arrays with nulls and then due to the lack of null sanity checks the CLI tool crashes down

**Comment by Jonida** [comment]
@kopcion @edavis10 @campmedia The issue is fixed here https://github.com/Shopify/shopify-cli/pull/2272 and it is part of the new version of the CLI 2.16. @raluka thanks!

**Comment by kopcion** [comment]
@Jonida the bug IS NOT fixed

**Comment by kopcion** [comment]
Please just change the number of threads to 1. At least as a quick fix... @gonzaloriestra
