### ISSUE TITLE
[Bug]: Unable to connect to Admin API of Dev Store

### ISSUE THREAD

**Issue by t6d** [Shopify/shopify-cli#2257]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

`shopify extension serve` should start the development server

### Actual behavior

`shopify extension serve` fails for checkout extensions due to an authentication issue with the Admin API. Before starting the development server, the Shopify CLI attempts to connect to the Admin API to fetch a list of product variants. This list is used to construct a Cart URL for checkout extensions – the so called resource URL. This URL is required to redirect extension authors to checkout so they can test their extension.

Manually specifying the URL via

```
shopify extension serve --resourceUrl=...
```

circumvents the issue as it results in omitting any API requests to the Shopify Admin API.

We validated that the CLI was logged into the correct partner organization and correct development store. However, the token used by the CLI seemingly had insufficient permissions to carry out the API request. We also observed that the dev store didn't appear in the user's identity targets. We suspect the root cause to be an identity issue, possibly just a delay in how settings are synced. Given that this would prevent partners from effectively testing their extensions, this warrants further investigation.

### Stack trace

```shell
https://github.com/Shopify/shopify-cli/blob/07968303b20c6cd2f4a4b4a2677aef696d55bd96/lib/project_types/extension/models/specification_handlers/checkout_ui_extension.rb#L33
```

### Reproduction steps

@lemonmade, can you or someone on your team please provide the exact steps to reproduce the problem?

### Operating System

MacOS Monterey 

### CLI version (run `shopify version` if you're not sure)

2.15.5

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

3.1.0

**Comment by gonzaloriestra** [comment]
Maybe @leleabhinav can help you with this. Otherwise, you can ask in `#identity-dev`.

**Comment by lemonmade** [comment]
@ecbrodie @jamesvidler can you please post the dev shop, organization, and app names you were able to replicate this issue with?

**Comment by ecbrodie** [comment]
For me:

- dev shop: https://evan-brodie-development-store.myshopify.com/
- Organization: "Evan Brodie Post Purchase"
- App Name: "access_scopes_test"

**Comment by sjanczy2** [comment]
Prerequisite: You will need to have a partners account and app with specific beta flags along with a dev shop with at least one product. You might also need shop beta flags.
Partners account beta flag: [link](https://partners.shopify.com/internal/betas/checkout_ui_extension)
App level beta flag: [link](https://app.shopify.com/services/internal/app_betas/checkout_ui_extension)
Shop beta flag #1: [link](https://app.shopify.com/services/internal/betas/shops/force_checkout_one)
Shop beta flag #2:[link](https://app.shopify.com/services/internal/betas/shops/checkout_one_argo_extensions)

Reproduction steps:
1. Navigate to folder where you will create extension
2. Run `shopify extension create --type checkout_ui_extension --name test`
3. In the prompt, select the app where you've added the beta flag
4. Select the language template to create the extension in
5. `cd test` to move into directory
6. Inside extension directory, run `shopify extension serve`
7. Select any prompts that appear as necessary
8. You should hit an error stating `Command not allowed with current login. Please check your login details with shopify whoami. You may need to request additional permissions for this action.`
9. Error has been reproduced.
[image](https://screenshot.click/Screen_Shot_2022-04-28_at_5.50.56_PM.png)

Workaround:
1. Navigate into your created dev shop
2. Grab the id of the variant under your product(for example `gid://shopify/ProductVariant/12345`, copy `12345`)
3. Navigate to the `.env` file of your extension
4. Add the following line to the .env file, replacing `ID` with the id from step 2: `EXTENSION_RESOURCE_URL=/cart/ID:1`
5. Run `shopify extension serve` again
6. Server should start properly

**Comment by ecbrodie** [comment]
Here's my results of @pepicrft's reproduction steps:

- `shopify version` --> 2.16.1.
- `echo $(brew --prefix shopify-cli)/gems` --> `/opt/homebrew/opt/shopify-cli/gems`
  -  However, I am going to use the latest version of the `shopify-cli` codebase for my reproduction, since this bug can be reproduced on both the "production" and the "development" version of the codebase.
- I logged in via `shopify login --store https://evan-brodie-development-store.myshopify.com` to `evan.brodie@shopify.com`
- These are the commands I executed in my successful reproduction of the issue, with commentary into what was happening when the following request IDs were printed:
  - `shopify extension create`:
    - After "Loading your apps...": `7c65e838-4903-4748-8ab8-154d1e6bd23c`
    - After selecting the app: `ed690c57-9057-4114-8e4a-e5412c966409`
  - `shopify extension serve`:
    - Immediate request occurs before any prompt: `cb80f8f9-ffae-45f1-9c73-009db023673c`
    - After answering No to "Are you working on a Shopify project on behalf of the Shopify partners org?": `7969d8b4-8405-40e6-adcf-9b204d379ef1`
    - After answering all remaining questions ("To which partner organization does this project belong?" and "To which app does this project belong?"), the message ".env saved to project root" is printed and the `.env` is written to. Two requests occur after this last message and before the "Command not allowed with current login" error: `a8113202-9bf2-4df2-bc6e-49a27c3cc165` and `839d0df8-385a-4357-97e1-e8c96ec111eb`.

**Comment by pepicrft** [comment]
Thanks a lot @ecbrodie. I couldn't find those requests in Splunk, but I found another one that seem to be the error that you are getting from the API:
- **Store**:
  - FQDN: [evan-brodie-development-store.myshopify.com](https://evan-brodie-development-store.myshopify.com/)
  - ID: 59587035298
  - Partners permalink: [Link](https://partners.shopify.com/internal/shops/59587035298)
- **Splunk**:
  - Event: [Link](https://logs.shopify.io/en-GB/app/search/search?q=search%20index%3Dmain%20shop_id%3D59587035298%20request_id%3D%22bbbbd8f7-3c77-4ca8-9a2c-745b6d7c109a%22&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-24h%40h&latest=now&sid=1651581919.197534_2522C1C5-7864-4C94-9683-25908386AE7A)
  - API error: `A valid access token was provided, but uuid=4949de9f-02ff-4193-8b9a-d245369f10e2 is not a valid identity account or partners collaborator for this shop.`
   - Identity account: [Link](https://accounts.shopify.com/services/accounts/144424567)

The error seems to be coming form [this line](https://github.com/Shopify/shopify/blob/main/components/access_and_auth/app/controllers/concerns/login_protection.rb#L304). Reading through the lines above that one make me think that the following lines lead to `user == nil`:

```rb
identity_account = shop.identity_accounts.find_by(uuid: token_info.sub)
user = identity_account&.user
```
And this one also fails to find the user because your store doesn't have the [`add_collaborator_auth_to_login_from_service`](https://app.shopify.com/services/internal/betas/shops/add_collaborator_auth_to_login_from_service) beta flag enabled:

```rb
collaborator_auth_login_enabled = shop.beta.enabled?(:add_collaborator_auth_to_login_from_service)
if user.nil? && collaborator_auth_login_enabled && IdentityAccount.can_find_partners_collaborator?(token_info)
  user = IdentityAccount.find_partners_collaborator(shop, identity_bearer_token, token_info.sub)
  identity_account = user&.identity_account
end
```

I lack a bit of product context around how we make partners collaborators of the store that they create. Is this something you might be able to shed some light on @stephszeto / @bgswan-shopify ?

**Comment by bgswan-shopify** [comment]
A partner can't be a collaborator of a dev store they have created because there will already be a user on the shop (the account owner) with Partner Organization business email.
It is possible for a partner to create another organization with a different organization business email and request collaborator access that way but that doesn't seem to be this issue here as [evan-brodie-development-store.myshopify.com](https://evan-brodie-development-store.myshopify.com/) only has a single user.

**Comment by bgswan-shopify** [comment]
I think the issue is because the user on the shop is [brodie.evan@gmail.com](mailto:brodie.evan@gmail.com) but the identity account being used is [evan.brodie@shopify.com](https://accounts.shopify.com/services/accounts/144424567)

**Comment by sjanczy2** [comment]
I can share my env details as well
Dev Shop: https://pet-store-plus-dev.myshopify.com/
Organization: Pet Store Plus Dev
App: pet_store_plus_checkout_dev

**Comment by stephszeto** [comment]
Still a little lost as to what the root cause of the problem is - Brian, can you elaborate on your comment? Also does this warrant a call to talk this through at this point?

**Comment by dmhenry** [comment]
@shauns This is the CLI <-> Identity issue referenced in Checkout UI stand-up.

**Comment by vividviolet** [comment]
@ecbrodie How did you create the Dev Store? Did you go through Services internal or through the Partner's dashboard?

For what it's worth I don't have any issues doing the following:
1. Logging into [partners.shopify.com](https://partners.shopify.com/) with `trish.ta@shopify.com`
2. Create a new store from this page `https://partners.shopify.com/<org-id>/stores`
3. Log into that store using `shopify login --store=<store>` and then running `serve` for any of my extensions

I'm thinking your issue could be related to how the Development store was created?

**Comment by dmhenry** [comment]
Hey, everyone. I tried a lot of variations on creating Development stores yesterday trying to figure this issue out. In the process I managed to mess up my identity and couldn't login to the CLI, Shopify.com, or Partners. I did manage to resolve the issue by clearing out my entire cached browser cookies. What's more, for me this fixed the underlying issue referenced in this thread (the CLI authenticates through a browser pop-up). Would one of you Checkout folks try clearing out your browser cache see if this doesn't resolve the issue for you as well?

@lemonmade @sjanczy2 @jamesvidler @vividviolet
