### ISSUE TITLE
[Bug]: .shopifyignore influence seems to have changed

### ISSUE THREAD

**Issue by venerated** [Shopify/shopify-cli#2261]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Before updating to the latest version of shopify-cli, I had a `src` folder in the `assets` folder to compile files from, which was listed in `.shopifyignore` as `assets/src` which was not an issue.

### Actual behavior

This morning I updated to the latest version from 2.15.0 I believe and this workflow no longer works. Now I get this error when trying to pull the theme:

<img width="840" alt="Screen Shot 2022-04-18 at 9 41 46 AM" src="https://user-images.githubusercontent.com/6817595/163841530-1316e513-07c8-437d-8167-33686e0a3714.png">

I have since moved the `src` folder to the root folder and it seems to be ignored, as I can use my usual workflow. I wanted to report this though incase it is an issue with .shopifyignore being respected.

### Reproduction steps

1. have a non-Shopify folder in one of the Shopify folders
2. add the folder to .shopifyignore
3. folder is detected by shopify-cli as being invalid

### Operating System

macOS 12.3.1

### CLI version (run `shopify version` if you're not sure)

2.15.6

### Shell

bash

### Ruby version (run `ruby -v` if you're not sure)

ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]

**Comment by gonzaloriestra** [comment]
Hi @venerated! Thanks for opening this issue.

You are right, this is something that changed since version 2.15.1, when we started to [block directories in theme assets](https://github.com/Shopify/shopify-cli/pull/1934). As you can see in [the documentation](https://shopify.dev/themes/architecture#directory-structure-and-component-types), subdirectories are not supported.

I know it was possible to ignore them before, but I hope it's not a problem. Other files added to `.shopifyignore` should be ignored as usual.
