### ISSUE TITLE
[Feature]: Looking for a production deployment document

### ISSUE THREAD

**Issue by zhaoyi0113** [Shopify/shopify-cli#2317]
### What type of project(s) will this request affect?

app, extension

### What type of change do you want to see?

New feature

### Overview

I followed that instruction https://shopify.dev/apps/getting-started/create to setup a local server to install an app which works great. But in production, I don't think I am going to use ngrok for the ssh tunnel. I can't find a doc about what the deployment should be in production.
Also is there any doc about that shopif cli does, like `shopify app serve`? In production environment, do I need to run this one? I think it depends on what production environment I am using. 

In the app created by shopify cli, there is a server listen on webhook, products-count, graphql, etc. entry point. Is there a document about what each of this is used for? 

Is there any doc to describe what happens underneath?

### Motivation

It is about the document in your website which doesn't cover much detailed information.

**Comment by amcaplan** [comment]
@shainaraskas maybe you can advise. I don't think we have much information about deployments on our [app dev site](https://shopify.dev/apps), but am I missing something?

Generally I think the tools the CLI provides are more about development than production, as in a production environment you'd simply run your app like any other web app. Though you do need to add a couple of ENV variables; that's come up before (https://github.com/Shopify/shopify-cli/issues/1018).

It might be really valuable to partners to give a short explanation of what you need in order to deploy an app to production. We certainly can't account for all scenarios, but there is basic information that's common to all environments that's simply not written anywhere on our dev site.

**Comment by towfiqi** [comment]
Any update on this?

**Comment by shainaraskas** [comment]
@towfiqi We currently have some production deployment guidance in our template repositories:

- [Node](https://github.com/Shopify/shopify-app-template-node/tree/cli_three)
- [PHP](https://github.com/Shopify/shopify-app-template-php/tree/cli_three)
- [Ruby](https://github.com/Shopify/shopify-app-template-ruby)

Some of this information might also be shared on Shopify.dev in the future.

**Comment by towfiqi** [comment]
@shainaraskas Thanks. Although I am hosting on a private server,  I checked the hosting documentation your shared.  

But I have a question that I cannot find the answer to. After publishing the app, how do I keep developing the app without changing the app url in the partner dashboard? Since the app's live server url is set in the partner dashboard url. It cannot be used with the local development right? 
Do I need to create a separate test app that will have the ngrok/cloudflare url as the partner dashboard's APP URL?

**Comment by gonzaloriestra** [comment]
You are right. The `--no-update` only works in some cases when you don't need to check the app in the store.

That's a good suggestion, we'll take it into account. Thank you!

**Comment by towfiqi** [comment]
Great to hear that :) Few months ago in the Shopify community forum, I saw a few devs frustrating over creating a different test app just for this.
I will create a test app for now.  Thanks!
