### ISSUE TITLE
theme serve: remember development theme across sessions for faster spin up time

### ISSUE THREAD

**Issue by itsanolive** [Shopify/shopify-cli#2435]
### What type of project(s) will this request affect?

theme

### What type of change do you want to see?

Substantial change to existing feature

### Overview

Change the default behavior of new store cli sessions to continue using the same development theme per developer+device, with maybe a flag option to start a new one, instead of uploading a brand new dev theme, similar to how it functions within a session.

### Motivation

This would dramatically increase efficiency in the dev process when working across multiple stores.

When logged into a shopify store, you can start and stop `shopify theme serve` and the cli will serve to the same development theme, which includes your user id and machine in the theme title. However, if you switch to another store and come back, running the same command will add an entirely new development theme (which takes multiple minutes) even though your old one still exists. You can see this by running `shopify theme list`.

**Comment by PaulNewton** [comment]
@itsanolive Also see vfonic's issues #2090 & #2385
particularly see this comment about a cli rewrite: https://github.com/Shopify/shopify-cli/issues/2090#issuecomment-1055558838 

When spinning up it should probably also confirm you want a new sync to happen , or be a config.
Everytime a new theme sync upload happens I have a deep breath moment where I have to double check what directory I'm and what store i'm connected too and that the cli isn't nuking the wrong theme. This is also problematic if your not in the correct directory and that location has NO theme files it will try to sync nothing for a long time. 

Compounding issue, these duplicate cli themes get the same name so in recovery situations, _such as getting settings_data.json of the **old** cli-theme_ ,  that name-ambiguity adds to the confusion when viewing theme lists and multiple names are the same.

Currently it starts pushing 10 minutes getting going when this happens in checking whoami then switching stores then the total spool up time uploading and any round tripping to get remote files from the OLD cli-theme.

This also effects project management since a new theme is created and we cannot reconnect `theme serve` to the the OLD cli-theme then the [cli-theme's 7 day expiry](https://shopify.dev/themes/tools/cli#development-themes:~:text=Development%20themes%20don%27t%20count%20toward%20your%20theme%20limit%2C%20and%20are%20deleted%20from%20the%20store%20after%20seven%20days%20of%20inactivity) starts; and it isn't clear if "inactivity" only counts cli|api activity, or it counts activity in the visual editor. So if you forget about this then any docs or communications with the old preview_theme_id param become defunct in short order.

Just a lot issues that overall create a lot of workflow friction for anyone working across multiple environments & properties.

related #2395 , #2397

**Comment by ADTC** [comment]
I think it would be more awesome if I can specify an existing unpublished theme for `theme serve` to simply plug into. The same command could also be used to specify a custom name to use or reuse (instead of the auto-generated name). It could pick the theme which has this name already, or upload a new development theme if none exists.

**(For safety, this should disallow any live theme.)**
```
theme serve -t 123456789012
theme serve -t My Development Theme
-t, --theme=NAME_OR_ID Theme ID or name of the remote theme.
```

### **My situation:**

Because of the enormous amount of time it takes for `theme serve` to upload an entire theme from scratch to a "development theme" I don't use this function. I instead use an unpublished theme to manually push and pull my changes to. It's simply faster and more predictable for me in my day-to-day workflow (sometimes switching between different stores).

But this means I lose all the benefits of `theme serve` like automatic real-time pushes, hot reloading, etc. There's also the problem that it takes **5 to 7 seconds** for Shopify CLI to boot up in Ruby on my system **on every command.** _(It used to be around 12 seconds, but seems to have improved with an SSD upgrade or a newer version of CLI.)_

If I can simply **always** reuse the same existing non-live theme with the `theme serve` command, it would potentially solve the above issue in a neat way that works for both unpublished themes and development themes. Instead of uploading the entire theme, it would only upload (same as `theme push`) the differences, then start a real-time sync session using the refreshed theme (same as the present-day `theme serve`).

**Comment by itsanolive** [comment]
Thanks @ADTC - this is only partially helpful since knowing the theme id ahead of serving is kind of annoying and requires another step. But still useful in certain cases.

This issue has mostly been alleviated by the new release that speeds up the upload considerably. Instead of taking minutes now, it takes 20 or so seconds to spin up. 

I do still think an additional flag in `serve` would be great to use a previous dev theme instead of starting a new one per session.

**Comment by vfonic** [comment]
Is there any progress on this? I'm writing this now because I have 6+ minutes of wait time because I just logged in to another store...

I'm literally waiting 6 minutes and then I'll have to login again because I'm working "live" with the client who owns two stores and I'm switching back and forth several times in these few hours. It's super annoying to have to wait so long.

/cc @gonzaloriestra
