### ISSUE TITLE
[Bug]: populate --images not supporting object

### ISSUE THREAD

**Issue by zifahm** [Shopify/shopify-cli#2527]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

app

### Expected behavior

`shopify populate --images={url:"imageurl"}` 

should work without any errors and should accept objects from the cli

### Actual behavior

Passing this cli command creates and error

The object is not getting parsed to json.

```
"problems"=>[{"path"=>["images", 0], "explanation"=>"Expected \"url:asdf\" to be a key-value object responding to `to_h` or `to_unsafe_h`."}
```

### Stack trace

```shell
┃ ✗ [{"message"=>"Variable $input of type ProductInput! was provided invalid value for images.0 (Expected \"url:asdf\" to be a key-value object responding to `to_h` or `to_unsafe_h`.)", "locations"=>[{"line"=>1, "column"=>24}], "extensions"=>{"value"=>{"title"=>"lively pond", "variants"=>[{"price"=>"9.00"}], "images"=>"url:asdf"}, "problems"=>[{"path"=>["images", 0], "explanation"=>"Expected \"url:asdf\" to be a key-value object responding to `to_h` or `to_unsafe_h`."}]]


```
```


### Reproduction steps

1. use the cli command `shopify populate products --images={url:asdf}`
2. this would create an error which says `should pass in an key value object`


### Operating System

Ubuntu 20.4

### CLI version (run `shopify version` if you're not sure)

2.21.0

### Shell

bash

### Ruby version (run `ruby -v` if you're not sure)

2.7.0p0

### What language and version are you using in your application?

_No response_

**Comment by sjb9774** [comment]
For whatever maintainer ends up looking at this, this appears to be an issue with the populate command code relying on the [OptionParser built-in type conversions](https://ruby-doc.org/stdlib-2.7.1/libdoc/optparse/rdoc/OptionParser.html#class-OptionParser-label-Type+Coercion) for strings, ints, lists, etc but there is no such converter for hashes/objects. A naive I believe fix is to modify the `input_options` method in `lib/shopify_cli/admin_api/populate_resource_command.rb` to check for a passed argument that is valid JSON and if so parse it to a hash and assign _that_ to `@input[field["name"]]` instead of assigning the string representation.
