### ISSUE TITLE
Testing Webhooks via the CLI

### ISSUE THREAD

**Issue by tylerball** [Shopify/shopify-cli#274]
Webhooks are hard. It would be great if developers could test their webhook code without having to do so from within the admin (Settings > Notifications > Webhooks > Send test notification).

Best webhook practice is to verify the authenticity of Shopify's request by comparing its HMAC, so unless we introduce some kind of "test mode" into our libraries we couldn't, say, just send a request from directly from the CLI to their server.

**Comment by nwtn** [comment]
Since the functionality exists in admin, can we have the CLI do a call to Partners that triggers the core functionality via Cusco?

**Comment by tanema** [comment]
This is really hard since we really dont have a schema or definition of webhooks. Our webhooks also don't always return the same thing. Then there is also the possibility that the developer wants to use the query which allows them to select which parts of the webhook they receive. 

I am certain that the webhooks team would love to standardize webhook output and be able to have full schemas like stripe or a company like that but I think we are a long time off of that.
