### ISSUE TITLE
Ngrok yields "Too Many Connections" Error during normal development

### ISSUE THREAD

**Issue by ezmiller** [Shopify/shopify-cli#449]
# Issue summary

Developing using ngrok to provide a tunnel from a local dev environment to the authorized "embedded" context in Shopify causes a "Too Many Connections" error:

![image](https://user-images.githubusercontent.com/772738/74499276-2f6be700-4eb1-11ea-8d09-bd0dd21ccd61.png)

This apparently is related to a limitation (or feature) of ngrok itself (see [here](https://stackoverflow.com/questions/40939587/ngrok-err-ngrok-702-too-many-connections) and [here](https://localwp.com/community/t/too-many-connections-error-another-err-ngrok-702-post/13612)). 

When it comes to development of apps, however, this limitation is pretty crippling. That's especially true with hot reloading enabled. Pretty much immediately you end up hitting the connection limit.

## Expected behavior

There should be no limit to connections for reloads so that hot reloading works and you don't have to wait a minute every other minute to see the changes you make take effect.

## Steps to reproduce the problem

1. Run an app dev environment with `shopify serve`.
1. Load the app page on whatever store it is installed
1. Keep reloading the page. After 4 or 5 times, depending on how many requests your page makes on each load, you should see the message pasted above.

## Specifications

- App type: node
- Operating System: mac
- Shell: zshrc
- Ruby version (ruby -v): 2.3.7

**Comment by tomblanchard** [comment]
@ezmiller Having the same issues, any update on this?

**Comment by tanema** [comment]
This is not something we can particularily help with. If you are using hot reloading, maybe add more delay to it so that you do not get a burst of requests if you hit save a few times.

There is also the option that you could buy a ngrok license to get around the limit. This limit is not imposed by us. It is ngrok.

**Comment by katiedavis** [comment]
To echo this, it seems like there's no way to 'turn off' hot reloading with next.js, I understand the frustration though. We will explore this in upcoming work on the node app.

**Comment by tomblanchard** [comment]
@tanema @katiedavis As much as I appreciate the effort gone into making app development for accessible (especially for us Node.js devs), it seems quite a shame to have to pay for a third party service license just to tip your toes into app development.

In the past I've used been able to get local apps up and running with https://localhost with a fake SSL certificate but it seems the new embedded app cookie requirements now stop this from working. Is there no way we can revisit this instead of having to rely on third party proxy services?

**Comment by tanema** [comment]
Because of SameSite requirements now required in Chrome, those cookies need to be secure, which means they can only be served over https. To do this locally, the easiest and most straight forward way is to use a tunnel.

**Comment by tomblanchard** [comment]
@tanema Yep you're totally right, it's just a shame the tunnel used (Ngrok) is so limited in terms of connections/minute.

The free plan allows 40 connections/minute which gets hit pretty easily with Next.js/hot reloading, the "basic" and "pro" plans up this limit to 60 connections/minute but it'll most likely still be reached with normal development/code changes. The next plan up is the "pro" plan which comes to 120 connections/minute which would probably be fine but it seems pretty ridiculous to suggest aspiring app devs to do this.

What does the workflow look like for internal apps at Shopify? Perhaps it'd be a good idea to add some info to the docs on how to get setup with https/localhost as an alternative to a third party tunnel? I've tried a lot of things but can't seem to get it working with the new cookie SameSite/secure requirements.

**Comment by dwixom** [comment]
^ Totally agreed on this @tomblanchard - [trying to walk through the tutorial here](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris) and I keep getting slammed with this message. Frustrating because Shopify is an otherwise developer-friendly system compared to other platforms, which is why I want to use it! But this is crippling during development.

**Comment by benhonda** [comment]
For those struggling with this issue, I recommend using an alternative to Ngrok that has https support and a higher connections limit, such as [Localtunnel](https://localtunnel.github.io/www/).

**Comment by riezahughes** [comment]
@benhonda i assume it'd just a matter of doing `npm run dev` and `npx localtunnel --port 300` seperately, while completely ignoring the shopify serve part command?

**Comment by niallr12** [comment]
@riezahughes That is exactly what I did. Also, don't forget to update your application URLs in your partner dashboard.

**Comment by Jeffthedevv** [comment]
I was having the same issues with hot reloading, but I'm on Brave and just turned off 'shield protection'. 
Seems to have solved the problem for now, but this is just a bandaid.

**Comment by manylov** [comment]
@niallr12 does this means that you should change localtonnel url in app settings at the every new session?

**Comment by OmarKhattab** [comment]
> @benhonda i assume it'd just a matter of doing `npm run dev` and `npx localtunnel --port 300` seperately, while completely ignoring the shopify serve part command?



This info was useful but its missing some detail.

So have your nodejs shopify app run `npm run dev` open a new tab in terminal and run `npx localtunnel --port 8081` 

Next go to https://partners.shopify.com/
open apps >> yourapp >> app setup >> Insert In URLs(Whitelisted redirection URL(s))

Once you whitelist your URL the issue is solved. 

In my case for app url I used: https://grumpy-beetle-44.loca.lt/
For the redirect URLS i used two 
1. http://127.0.0.1:8081/
2. https://grumpy-beetle-44.loca.lt/auth/callback

The URL is generated by localtunnel so copy and paste it

other source: https://stackoverflow.com/questions/55918320/oauth-error-invalid-request-the-redirect-uri-is-not-whitelisted

**Comment by niallr12** [comment]
> @niallr12 does this means that you should change localtonnel url in app settings at the every new session?

Yes it does. I need to go into my app settings and update it each time I run a new session. This is a bit annoying but definitely better than using ngrok.

**Comment by ozeron** [comment]
@niallr12 @OmarKhattab 
No, you can use `-s` option to reserve your subdomain. 
So you run your regular `lt` command, then add `-s mycooluniqsubdomain` 

Then you should get access to `mycooluniqsubdomain.loca.lt` if it is available

**Comment by niallr12** [comment]
@ozeron I did not know that! Thanks for the tip.

**Comment by moskalukigor** [comment]
Hello everyone.
I am using npx localtunnel, but I get this error from Shopify:
`504 Gateway Time-out`

App URL:
`https://devshopify.loca.lt/`

Allowed redirection URL (s):
```
http://127.0.0.1:8081/
https://devshopify.loca.lt/auth/callback
```

terminal command:
`lt --port 8081 -s devshopify`

Please tell me what could be the problem? tnx

**Comment by g-hamilton** [comment]
I'm fed up with this. Even if  I wait 10 mins and try to load my app once, without any fast reloads, I can't even load my app. Apparently it's making 44 connections just to load???

![image](https://user-images.githubusercontent.com/56267983/125198551-317ad680-e25a-11eb-8df7-d91e9330257a.png)

**Comment by adrianghub** [comment]
C'mon 😅

![image](https://user-images.githubusercontent.com/44274979/127619833-5095de5f-0c3a-4cb8-b384-ea18586736ad.png)

**Comment by KennyKYLam** [comment]
Happening for me too :(
