### ISSUE TITLE
Support package install via npm

### ISSUE THREAD

**Issue by gfscott** [Shopify/shopify-cli#811]
Now that we support installing as a package, we should enable installation via npm.

```console
$ npm i -g @shopify/shopify
```

(Looks like the un-namespaced [`shopify`](https://www.npmjs.com/package/shopify) would require intervention of some sort, for which I'm unsure of the appetite.)

**Comment by tanema** [comment]
wait, why would we install a ruby application through npm?

**Comment by gfscott** [comment]
People install all kinds of things with npm. [Netlify](https://www.netlify.com/products/dev/#how-it-works) and [Vercel](https://vercel.com/download) both install their CLI tooling that way. Just seems like a modest convenience win.

**Comment by isAdrisal** [comment]
+1 to this. My specific use case is for a team using shopify-cli to integrate `theme-check` as part of the dev experience for linting.

We currently use `stylelint` and `eslint` which are installed and kept up to date via `npm` (actually `yarn` in our case) via `package.json` so that the team are always using the same version of those packages.

Currently, team members must manually update `shopify-cli` in order to update `theme-check` and we all know how that story goes...
