### ISSUE TITLE
Shopify connect fails within a server without graphic interface

### ISSUE THREAD

**Issue by luilver** [Shopify/shopify-cli#855]
# Issue summary

Following [Core Commands](https://shopify.github.io/shopify-app-cli/core/) documentation I executed `shopify connect` command and it showed "Please open this URL in your browser". Due to I'm in a server without a browser I copied the link and opened in another computer resulting in a «Unable to connect» error                                                  

## Expected behavior

Connect command should consider this scenario and prepend an «use this link if you have a browser within this computer» or «create an ngrok tunnel if you don't have a browser on a server-like cli» and ask for ngrok url before building the link with localhost:3456.

## Actual behavior

After shopify authentication request, browser tries to redirect to `localhost:3456/?code=...` resulting in the following error:

<details>
Unable to establish a connection to the server at 127.0.0.1:3456.
</details>

## Steps to reproduce the problem

1. Install [shopify-cli 1.1.1](https://github.com/Shopify/shopify-app-cli/releases/download/v1.1.1/shopify-cli-1.1.1.deb)
2. Run command `shopify create`
3. When message «Please open this URL in your browser:» appears copy it
4. Paste URL in another host browser. 

## Specifications

- App type: Shopify CLI
- Operating System: Ubuntu 20.04 Server
- Shell: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
- Ruby version (ruby -v): ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

**Comment by paulomarg** [comment]
Hello there! You are right, the CLI currently assumes you'll be able to open the website on the same computer that's running it. Thank you for the report.

Until this is handled, you could try working around it by using a headless browser, or if you're in a VM, forwarding the 3456 port from your host to your container, so `localhost:3456` ends up going into the VM.

**Comment by luilver** [comment]
Hi Paulo,

Thanks a lot for confirming my report.

Yes, in deed I actually bypassed this unexpected behaviour opening an
ngrok tunnel upon localhost:3456.

I have received another error and I have been reported it too on #856

Thanks you for your support.

Regards,

Luilver

**Comment by ismailalabou** [comment]
> Hello there! You are right, the CLI currently assumes you'll be able to open the website on the same computer that's running it. Thank you for the report.
> 
> Until this is handled, you could try working around it by using a headless browser, or if you're in a VM, forwarding the 3456 port from your host to your container, so `localhost:3456` ends up going into the VM.

'how can I do this ??; I'm facing the same issue when working with a VM,

**Comment by AldeBaranOZ** [comment]
Has there been any progress on this issue? 

Having to use a browser makes the whole point of having a cli script quite pointless. 

At the very least, is there a way to copy the cookie or some other auth token across from a machine with a GUI or something?

**Comment by immakdas** [comment]
I can not get APP Approve due to this. Please provide a steps how to resolve this

**Comment by axtricssolutions** [comment]
Hi All,

I am facing the exact same issue.

I have created an App using Shopify CLI 3.0 and when i am using the `npm run deploy` command on my remote Ubuntu machine then Shopify is trying to authenticate by opening up the browser. Because the server is not having GUI browser available and as a result it gets failed.

Is there a way to authenticate the App without the need of login to Partners account? I noticed Shopify provides [CLI token](https://shopify.dev/apps/tools/cli/ci-cd) for CI/CD so maybe that is something we can look for? 

A help here is highly appreciated.

**Comment by priyankatotala** [comment]
Hi,
I also face the same issue while trying to approve the app from my partners account login.
I am in the terminal connected to my web server where my shopify app is hosted .I have installed shopicy CLI 3.45.1 version.
I execute this command
**shopify theme list --store=modappsteststore.myshopify.com**
and I get to see this 

To run this command, log in to Shopify Partners.
👉 Press any key to open the login page on your browser
after I press any key and I get this to see

Auto-open timed out. Open the login page: Log in to Shopify Partners ( http://accounts.shopify.com/oauth/authorize?client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456&state=f1d1c05346cdfa4a7342a8e73b8bae9301f1096e89ebe5acd196ca55011d&response_type=code&code_challenge_method=S256&code_challenge=pRVdXjdh3lEa_5toYTE93GLcfbbfnyNct5kYXnH6XmY )

WHeN i OPEN THE LINK IN MY BROWSER AND and it navigates to the login section for the partners account and when I chosse my partners email id and password, I was redirected to this error
"This site can’t be reached127.0.0.1 refused to connect." and this is my url. But according to shopify docs, its has to show login approved. and I should see the respective details in cli.

I have no clue why I could not get the app approve. This is very crucial since I need to create app extension for m exisitng app.
